# Generated by Django 5.2.1 on 2025-05-30 16:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname_pets', models.CharField(max_length=150, verbose_name='Кличка')),
                ('breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('view', models.CharField(max_length=100, verbose_name='Вид')),
                ('gender', models.CharField(choices=[('male', 'Самец'), ('female', 'Самка')], max_length=10, verbose_name='Пол')),
                ('color', models.CharField(max_length=100, verbose_name='Окрас')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Информация о животном')),
            ],
            options={
                'verbose_name': 'Животное',
                'verbose_name_plural': 'Животные',
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_shelter', models.CharField(max_length=255, verbose_name='Название приюта')),
                ('address_shelter', models.TextField(verbose_name='Адрес приюта')),
                ('email_shelter', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email приюта')),
                ('telephone_shelter', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон приюта')),
                ('capacity', models.PositiveIntegerField(verbose_name='Вместимость')),
            ],
            options={
                'verbose_name': 'Приют',
                'verbose_name_plural': 'Приюты',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=150, verbose_name='Имя администратора')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Администратор сайта',
                'verbose_name_plural': 'Администраторы сайта',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Усыновлено')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.animal', verbose_name='Животное')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на усыновление',
                'verbose_name_plural': 'Заявки на усыновление',
            },
        ),
        migrations.CreateModel(
            name='FoundAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Кличка')),
                ('view', models.CharField(max_length=100, verbose_name='Вид')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Порода')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Самец'), ('female', 'Самка')], max_length=10, null=True, verbose_name='Пол')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Окрас')),
                ('place_found', models.TextField(verbose_name='Место находки')),
                ('date_found', models.DateField(default=django.utils.timezone.now, verbose_name='Дата находки')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='found_animals/', verbose_name='Фото')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('is_matched', models.BooleanField(default=False, verbose_name='Совпадение найдено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_animals', to=settings.AUTH_USER_MODEL, verbose_name='Нашёл')),
            ],
            options={
                'verbose_name': 'Найденное животное',
                'verbose_name_plural': 'Найденные животные',
            },
        ),
        migrations.CreateModel(
            name='LostAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lostie_name', models.CharField(max_length=150, verbose_name='Кличка')),
                ('view', models.CharField(max_length=100, verbose_name='Вид')),
                ('breed', models.CharField(blank=True, max_length=100, null=True, verbose_name='Порода')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Самец'), ('female', 'Самка')], max_length=10, null=True, verbose_name='Пол')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Окрас')),
                ('place_of_loss', models.TextField(verbose_name='Место пропажи')),
                ('date_of_loss', models.DateField(default=django.utils.timezone.now, verbose_name='Дата пропажи')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('reward', models.PositiveIntegerField(blank=True, null=True, verbose_name='Награда (руб.)')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочно')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lost_animals/', verbose_name='Фото животного')),
                ('date_reported', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи объявления')),
                ('is_found', models.BooleanField(default=False, verbose_name='Найдено')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Потерянное животное',
                'verbose_name_plural': 'Потерянные животные',
            },
        ),
        migrations.CreateModel(
            name='FoundReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_found', models.TextField(blank=True, null=True, verbose_name='Место находки')),
                ('date_found', models.DateField(default=django.utils.timezone.now, verbose_name='Дата находки')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='found_reports/', verbose_name='Фото')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('the_finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Нашёл')),
                ('losties', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lostanimal', verbose_name='Потерянное животное')),
            ],
            options={
                'verbose_name': 'Запись о находке',
                'verbose_name_plural': 'Записи о находках',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='animals/', verbose_name='Фото')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app.animal', verbose_name='Животное')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.shelter', verbose_name='Приют'),
        ),
        migrations.CreateModel(
            name='ShelterRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя представителя')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('shelter', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representative_link', to='app.shelter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_representative_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Представитель приюта',
                'verbose_name_plural': 'Представители приютов',
            },
        ),
    ]
