# Generated by Django 5.2.1 on 2025-06-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Подтверждён администратором'),
        ),
    ]
