# Generated by Django 5.2.1 on 2025-06-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shelter_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='size',
            field=models.CharField(choices=[('small', 'Маленький'), ('medium', 'Средний'), ('large', 'Крупный')], default='medium', max_length=10, verbose_name='Размер'),
        ),
    ]
