# Generated by Django 5.2.1 on 2025-06-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_animal_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='city',
            field=models.CharField(default='Не указан', max_length=100, verbose_name='Город'),
        ),
    ]
