# Generated by Django 5.2.1 on 2025-06-05 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundreport',
            name='losties',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.lostanimal', verbose_name='Потерянное животное'),
        ),
    ]
