# Generated by Django 5.2.1 on 2025-06-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_foundanimal_latitude_foundanimal_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundanimal',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='lostanimal',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
