# Generated by Django 5.2.1 on 2025-06-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_foundanimal_is_deleted_lostanimal_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='age',
        ),
        migrations.AddField(
            model_name='animal',
            name='age_months',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст (месяцев)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='age_years',
            field=models.PositiveIntegerField(default=0, verbose_name='Возраст (лет)'),
        ),
    ]
